### ISSUE TITLE
install Java 17

### ISSUE THREAD

**Issue by gborri** [mingchen/docker-android-build-box#100]
Hello,

do you think is it possible to install java 17?

thanks
Giovanni

**Comment by master-bob** [comment]
Hello,

What is the benefit of using Java 17?

**Comment by gborri** [comment]
the possibility to use Gradle 8.0-rc3 that have java 17 as prerequisite.

**Comment by master-bob** [comment]
Where are you seeing that?

The [compatibility notes](https://docs.gradle.org/8.0-rc-3/userguide/compatibility.html) for 8.0-rc3 say otherwise:
> A Java version between 8 and 19 is required to execute Gradle. Java 20 and later versions are not yet supported.

**Comment by master-bob** [comment]
Sorry, but the image does not appear to have been attached correctly.

**Comment by gborri** [comment]
sorry, i reply to email.

Here you are.

![image](https://user-images.githubusercontent.com/3479510/217321409-0fe3623d-72ee-4e9a-967d-c03c44c53437.png)

**Comment by master-bob** [comment]
Yeah, so technically speaking that's an issue with the Android Gradle plugin and not with Gradle itself. What version of the Android Gradle plugin is being used? [Version 7.4.0 requires JDK 11](https://developer.android.com/studio/releases/gradle-plugin#compatibility-7-4-0).

**Comment by gborri** [comment]
the point is that we want to build using Kotlin 1.8 that require Gradle 8.0 that require java 17.

I cannot use Gradle 8.0 with AGP 7.4.0.

Is so difficult to include java 17?

**Comment by philiposD** [comment]
I'm also facing the same issue, cannot build with Java 11

**Comment by gborri** [comment]
Gradle 8.0 require agp 8.

Il mar 7 feb 2023, 18:45 Leonardo Canessa ***@***.***> ha
scritto:

**Comment by master-bob** [comment]
The email missed my edit which I made not long after the comment. I've included it below for your convenience, with the important part bolded:

> e: **Nonetheless, I do think that an upgrade to Java 17 should be made.** In the meantime you can use the 7.4 Android Gradle plugin.

**Comment by gborri** [comment]
can i ask you why?

Il giorno sab 11 feb 2023 alle ore 21:31 Leonardo Canessa <
***@***.***> ha scritto:

**Comment by master-bob** [comment]
Why what? I don't understand. The point of that sentence is that I think Java 17 should be added to this project.

**Comment by gborri** [comment]
Sorry, I have read the opposite. my mistake.


Il giorno dom 12 feb 2023 alle ore 15:00 Leonardo Canessa <
***@***.***> ha scritto:

**Comment by master-bob** [comment]
Va bene.  Capisco che abbiamo un problema di barriera linguistica. 😅  Saluti e grazie per aver fatto il rapporto per cominciare.  👍 (Thank you Google Translate)

**Comment by gborri** [comment]
No, è che ho letto un non che non c'era. :-)

Il giorno dom 12 feb 2023 alle ore 15:13 Leonardo Canessa <
***@***.***> ha scritto:

**Comment by master-bob** [comment]
@gborri and @philiposD , just wanted to let y'all know that Java 17 is not installed in this container and on dockerhub. :+1:
