### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by philiposD** [mingchen/docker-android-build-box#102]
I'm getting this error on step 15/26

`#19 43.74 Warning: An error occurred while preparing SDK package NDK (Side by side) 25.2.9519653: No space left on device.`

Did someone else encounter this issue before?

**Comment by master-bob** [comment]
I suspect that may be an issue with the amount of space available on your disk drive, or the amount of space you are allocating to the docker container.

The following website, which I've taken a glance at, looks like it has some pointers: https://www.maketecheasier.com/fix-linux-no-space-left-on-device-error/

**Comment by philiposD** [comment]
Hi @master-bob, I've managed to deal with this issue by increasing the space in Docker Desktop, thanks!
