### ISSUE TITLE
Docker container fails android build with DaemonDisappearedException

### ISSUE THREAD

**Issue by Obolrom** [mingchen/docker-android-build-box#109]
I have an android multimodule project https://github.com/Obolrom/Podcaster on `dev` branch.

I run container with next command.

`docker run --rm -v pwd:/project  -v "$HOME/.dockercache/gradle":"/root/.gradle"   mingc/android-build-box bash -c 'cd /project; ./gradlew build'`

Build with no cache fails all the time. But after the second execution build finishes successfully. 
Even option `--no-daemon` or `--daemon` has no effect.

How to fix this problem?

**Comment by master-bob** [comment]
Hmm, maybe you have a memory issue? If you run it with no cache, does your system memory max out? Or is the docker container set to use too little memory?

Also your project needs to add the JVM maxminmetaspace value, spelling could be wrong. See gradle/gradle#19750.

**Comment by Obolrom** [comment]
@master-bob I think that 4 gigabytes of memory should be enough for the build. 10 out of 16 gigabytes of RAM is used during assembly. I will try to add metaspaceSize

**Comment by master-bob** [comment]
I can not recreate this error. When I build the dev branch of your project I get other errors. See attached files for build logs of the current dev branch and of 2 weeks ago.

[2023-03-06_podcaster-dev-buildLog-past.txt](https://github.com/mingchen/docker-android-build-box/files/10900425/2023-03-06_podcaster-dev-buildLog-past.txt)
[2023-03-06_podcaster-dev-buildLog.txt](https://github.com/mingchen/docker-android-build-box/files/10900427/2023-03-06_podcaster-dev-buildLog.txt)

Unless there are more updates, I suggest this issue be closed.

**Comment by Obolrom** [comment]
@master-bob Yeah, I think we close the issue. Thank you anyway :)
