### ISSUE TITLE
docker build -t android-sdk .  run very slow

### ISSUE THREAD

**Issue by AlbertShen0211** [mingchen/docker-android-build-box#117]
hi , docker build -t android-sdk . The command run very slow, seems like died when echo  # NDK                                                                                                                                                        
 => => # Installing ndk;25.2.9519653 . why? My project used native lang to devep, no need fastlane ,jenkins,some inpendence such as cordova ionic ?

**Comment by master-bob** [comment]
Hi AlbertShen0211,

Unless you are making changes to the Dockerfile yourself, there is usually no reason to build the image. You can just pull the image, which is just a download, and then use the already built image.

You pull the image by:
```sh
# docker pull mingc/android-build-box:latest
```
or you can specify the specific tag
```sh
docker pull mingc/android-build-box:1.25.0
```

Then you can use the image by doing something like the following:
```sh
# cd <project_working_directory>
# docker run --rm -v `pwd`:/project  -v "$HOME/.dockercache/gradle":"/root/.gradle"   mingc/android-build-box bash -c 'cd /project; ./gradlew build'
```

**Comment by AlbertShen0211** [comment]
More than 10G images compiled according to the latest Dockerfile? Is ubuntu dependency necessarily included？

**Comment by master-bob** [comment]
Yes, a dependency on a operating system is needed. The Ubuntu 20.04 LTS image was chosen and its something <100 MB.

I'm not at my computer at the moment so from what I remember the main offenders for this image are something like platform Tools <6G, Ndk <2GB, the build tools <4GB, and Flutter <2gb. If you have the image you can run some variation of `du - h --max-depth=4` from `/` to see for yourself.

**Comment by AlbertShen0211** [comment]
Can this project image  be built using Kaniko tools？
