### ISSUE TITLE
platform-tools/api/api-versions.xml java.io.IOException: Stream closed

### ISSUE THREAD

**Issue by kim-can** [mingchen/docker-android-build-box#126]
cannot load api descriptions from /opt/android-sdk/platform-tools/api/api-versions.xml java.io.IOException: Stream closed
	at java.base/java.util.zip.InflaterInputStream.ensureOpen(InflaterInputStream.java:68)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:122)

**Comment by master-bob** [comment]
That's a bummer. I get how frustrating it is to meet an exception.

Per [this](https://stackoverflow.com/questions/68634807/cannot-load-api-descriptions-from-android-sdk-platform-tools-api-api-versions) I think the 31.0.2 platform-Tools needs to be installed.

Until that Version is added to this project, you can Cache the Android SDK and then use the sdkmanager to install the related platform-Tools.

**Comment by master-bob** [comment]
Try using the latest version, as of now it has the 31.0.2 platform tools.
