### ISSUE TITLE
No usable tags in repo or Docker Hub

### ISSUE THREAD

**Issue by nicholasmarais1158** [mingchen/docker-android-build-box#13]
We use this box through BitBucket Pipelines. We recently had an issue which caused all out builds to fail (see https://github.com/mingchen/docker-android-build-box/issues/11).

We declare the build image like this;
`image: mingc/android-build-box`
which targets the $latest configuration.

For the sake of reproducible builds, I'd love to specify the build image like this;
`image: mingc/android-build-box:{version}` (see [docs](https://confluence.atlassian.com/bitbucket/use-docker-images-as-build-environments-792298897.html))

Currently this repo has an unhelpful 'v1.0.0' tag (also in Docker Hub) from over a year ago.

I'd like to suggest that tags are added more frequently once the config is proven stable.

**Comment by mingchen** [comment]
tag v1.1.0 added for latest stable image.
