### ISSUE TITLE
Fixed Flutter versions

### ISSUE THREAD

**Issue by deandreamatias-worldline** [mingchen/docker-android-build-box#142]
On [compatibility matrix](https://github.com/mingchen/docker-android-build-box/blob/master/COMPATIBILITY.md#various-installed-software-versions-matrix), the last Flutter version tagged (1.25.0) is 3.7.7
Will be useful if create a tag version for the new Flutter versions 3.10.6 and 3.13.1

**Comment by mingchen** [comment]
New tag 1.26.0 on the latest code.
If you would like other flutter version, feel free to send PR.

**Comment by deandreamatias-worldline** [comment]
Thanks!
I don't know if like contributor, I can create tags on project. If 1.26.0 is the new tag, can be use to identify 3.13.1 flutter version but the 3.10.6 version do not have tag :(
