### ISSUE TITLE
SDK 34

### ISSUE THREAD

**Issue by GrzegorzRussek** [mingchen/docker-android-build-box#160]
Are there any plans to support SDK 34?

**Comment by master-bob** [comment]
The `latest` version supports SDK 34 and Build tools 34 as well as reflected at the end of the [DockerHub page](https://hub.docker.com/r/mingc/android-build-box/).

> Android SDKs, Build tools, etc Installed:</p>
> 
> 
> Path | Version | Description | Location
> -- | -- | -- | --
> build-tools;27.0.0 | 27.0.0 | Android SDK Build-Tools 27 | build-tools/27.0.0
> build-tools;27.0.1 | 27.0.1 | Android SDK Build-Tools 27.0.1 | build-tools/27.0.1
> build-tools;27.0.2 | 27.0.2 | Android SDK Build-Tools 27.0.2 | build-tools/27.0.2
> build-tools;27.0.3 | 27.0.3 | Android SDK Build-Tools 27.0.3 | build-tools/27.0.3
> build-tools;28.0.0 | 28.0.0 | Android SDK Build-Tools 28 | build-tools/28.0.0
> build-tools;28.0.1 | 28.0.1 | Android SDK Build-Tools 28.0.1 | build-tools/28.0.1
> build-tools;28.0.2 | 28.0.2 | Android SDK Build-Tools 28.0.2 | build-tools/28.0.2
> build-tools;28.0.3 | 28.0.3 | Android SDK Build-Tools 28.0.3 | build-tools/28.0.3
> build-tools;29.0.0 | 29.0.0 | Android SDK Build-Tools 29 | build-tools/29.0.0
> build-tools;29.0.1 | 29.0.1 | Android SDK Build-Tools 29.0.1 | build-tools/29.0.1
> build-tools;29.0.2 | 29.0.2 | Android SDK Build-Tools 29.0.2 | build-tools/29.0.2
> build-tools;29.0.3 | 29.0.3 | Android SDK Build-Tools 29.0.3 | build-tools/29.0.3
> build-tools;30.0.0 | 30.0.0 | Android SDK Build-Tools 30 | build-tools/30.0.0
> build-tools;30.0.1 | 30.0.1 | Android SDK Build-Tools 30.0.1 | build-tools/30.0.1
> build-tools;30.0.2 | 30.0.2 | Android SDK Build-Tools 30.0.2 | build-tools/30.0.2
> build-tools;30.0.3 | 30.0.3 | Android SDK Build-Tools 30.0.3 | build-tools/30.0.3
> build-tools;31.0.0 | 31.0.0 | Android SDK Build-Tools 31 | build-tools/31.0.0
> build-tools;32.0.0 | 32.0.0 | Android SDK Build-Tools 32 | build-tools/32.0.0
> build-tools;32.1.0-rc1 | 32.1.0 rc1 | Android SDK Build-Tools 32.1-rc1 | build-tools/32.1.0-rc1
> build-tools;33.0.0 | 33.0.0 | Android SDK Build-Tools 33 | build-tools/33.0.0
> build-tools;33.0.1 | 33.0.1 | Android SDK Build-Tools 33.0.1 | build-tools/33.0.1
> build-tools;33.0.2 | 33.0.2 | Android SDK Build-Tools 33.0.2 | build-tools/33.0.2
> build-tools;34.0.0 | 34.0.0 | Android SDK Build-Tools 34 | build-tools/34.0.0
> build-tools;34.0.0-rc1 | 34.0.0 rc1 | Android SDK Build-Tools 34-rc1 | build-tools/34.0.0-rc1
> build-tools;34.0.0-rc2 | 34.0.0 rc2 | Android SDK Build-Tools 34-rc2 | build-tools/34.0.0-rc2
> build-tools;34.0.0-rc3 | 34.0.0 rc3 | Android SDK Build-Tools 34-rc3 | build-tools/34.0.0-rc3
> emulator | 32.1.15 | Android Emulator | emulator
> ndk;26.1.10909125 | 26.1.10909125 | NDK (Side by side) 26.1.10909125 | ndk/26.1.10909125
> platform-tools | 34.0.5 | Android SDK Platform-Tools | platform-tools
> platforms;android-27 | 3 | Android SDK Platform 27 | platforms/android-27
> platforms;android-28 | 6 | Android SDK Platform 28 | platforms/android-28
> platforms;android-29 | 5 | Android SDK Platform 29 | platforms/android-29
> platforms;android-30 | 3 | Android SDK Platform 30 | platforms/android-30
> platforms;android-31 | 1 | Android SDK Platform 31 | platforms/android-31
> platforms;android-32 | 1 | Android SDK Platform 32 | platforms/android-32
> platforms;android-33 | 3 | Android SDK Platform 33 | platforms/android-33
> platforms;android-33-ext4 | 1 | Android SDK Platform 33-ext4 | platforms/android-33-ext4
> platforms;android-33-ext5 | 1 | Android SDK Platform 33-ext5 | platforms/android-33-ext5
> platforms;android-34 | 2 | Android SDK Platform 34 | platforms/android-34
> platforms;android-34-ext8 | 1 | Android SDK Platform 34-ext8 | platforms/android-34-ext8

Do you have any suggestions on how to better reflect this in the Readme?
