### ISSUE TITLE
Flutter versone 3.22.3

### ISSUE THREAD

**Issue by gborri** [mingchen/docker-android-build-box#199]
hello, do you think is it possible to have a tag with 3.22.3 flutter version?
we have not yet tested software with 3..24.0 version.

let me know
thanks in advance
Giovanni

**Comment by master-bob** [comment]
Hi Hi,

Tag 1.28.0 uses Flutter version 3.19.2. If you are not needing any of the changes made between 3.19.2 and 3.22.3, I would suggest to just use the 1.28.0 tag. However if you are needing some changes then I think your best bet is to build the project manually.

I am unavailable at the moment to make any changes.

Cheers and good luck.
