### ISSUE TITLE
Android builds are now failing, as of 3 November 2018

### ISSUE THREAD

**Issue by ozmium** [mingchen/docker-android-build-box#22]
I now get this error at the assembleDebug stage, when building an Android project in Bitbucket Pipelines:

```
pipelines:
  default:
    - step:
        script:
          - chmod +x gradlew
          - ./gradlew assembleDebug
```

```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 23s
```

It was working fine yesterday. And it happens on projects that don't use the NDK.

How do we specify to use an older Docker image, instead of `image: mingc/android-build-box:latest` ?

---------

Update: Using an older image like this works for me:
```
image: mingc/android-build-box:v1.1.2
```

Using the tags from Docker Hub: https://hub.docker.com/r/mingc/android-build-box/tags/

However this image is 10 months old. **Could you please add a new Docker tag for this release point:** https://github.com/mingchen/docker-android-build-box/commit/6bf848221a06b799f579068333ee64ef51a0738b (it's everything up to 2 November 2018)

**Comment by mingchen** [comment]
Please use `mingc/android-build-box:v1.2.0`
