### ISSUE TITLE
Is there a way to cache Android emulator image downloads?

### ISSUE THREAD

**Issue by ozmium** [mingchen/docker-android-build-box#23]
The dependency cache for gradle works well, with the following lines in the YML file:

<pre>
pipelines:
  default:
    - step:
        <b>caches:</b>
          <b>- gradle</b>
</pre>

Bitbucket Pipelines will retain many gradle downloads in **~/.gradle/caches**

Is there a way to do the same thing for the Android emulator image downloads? These are large downloaded files which are usually stored in **~/.android/avd** (see [here](https://stackoverflow.com/questions/13095718/where-are-android-emulator-image-stored))

You can see examples of emulator image downloads [here](http://ady.my/viewer/system-image/index.html).

**Comment by mingchen** [comment]
It can be.

    image: mingc/android-build-box:latest

    pipelines:
      default:
        - step:
            caches:
              - gradle
              - gradlewrapper
              - androidavd
            script:
              - bash ./gradlew assemble
    definitions:
      caches:
        gradlewrapper: ~/.gradle/wrapper
        androidavd: ~/.android/avd

Reference: https://confluence.atlassian.com/bitbucket/caching-dependencies-895552876.html
