### ISSUE TITLE
android iterative build

### ISSUE THREAD

**Issue by bam80** [mingchen/docker-android-build-box#31]
Hi,
I would like to use this docker for Android project iterative build.
Could you please help me if it can be achieved? I'm not fluent in docker.

Here is assumed workflow:
- prepare the sources in my Android project folder `~/android `
- build the project with docker using `-v` flag:
`docker run --rm -v ~/android:/project ...`.
It's first time long time build, but the built artifacts should be saved for re-using in further builds.
- change source code of the project as needed, commit the changes to git
- run iterative build of the project in docker using artifacts from the previous build. This time the build should be fast.

**Comment by mingchen** [comment]
You can, just remove `--rm` parameter to let docker keep the state from its last run.
```
docker run -v ~/android:/project ....
```
