### ISSUE TITLE
Consider removing old Build Tools and old Android Platform versions

### ISSUE THREAD

**Issue by ozmium** [mingchen/docker-android-build-box#45]
Some of the Build Tools versions and Android Platform versions in the Docker container are very old. It's unlikely they will be used, because the Google Play Store requires a strict minimum version to be used, to publish app updates. Here are some examples of the requirements:

* https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html -- targetSdkVersion 26 (and buildToolsVersion 26) required from November 2018 onwards
* https://android-developers.googleblog.com/2019/02/expanding-target-api-level-requirements.html -- targetSdkVersion 28 (and buildToolsVersion 28) required from November 2019 onwards

Removing the old versions will generate a smaller and more efficient Docker image, which will load faster on CI Build machines.

The Docker Hub page shows that installing the Build Tools and Android Platform contribute a very large portion to the overall Docker image size. For example, [version 1.17 of the image](https://hub.docker.com/layers/mingc/android-build-box/1.17.0/images/sha256-d614f6ee87b6391eec7ef00458d4de04180ae876d9456a3f67172ff1bddfaffd?context=explore) uses 4.95 GB to install all these tools.

For example, consider removing the following old platform versions:

* "platforms;android-24"
* "platforms;android-23"
* "platforms;android-22"
* "platforms;android-21"
* "platforms;android-20"
* "platforms;android-19"
* "platforms;android-18"
* "platforms;android-17"
* "platforms;android-16"

And old build tools:

* "build-tools;24.0.3"
* "build-tools;24.0.2"
* "build-tools;24.0.1"
* "build-tools;24.0.0"
* "build-tools;23.0.3"
* "build-tools;23.0.2"
* "build-tools;23.0.1"
* "build-tools;22.0.1"
* "build-tools;21.1.2"
* "build-tools;20.0.0"
* "build-tools;19.1.0"
* "build-tools;18.1.1"
* "build-tools;17.0.0"

It may be possible to also remove all the [Google APIs](https://stackoverflow.com/questions/32084413/what-is-the-difference-between-google-apis-in-android-sdk) as well, because they only worked for platforms 16-24. I'm not 100% sure about this, but the old Google APIs (V1) for Google Maps does not work anymore, as per: https://stackoverflow.com/questions/34572026/error-inflating-class-com-google-android-maps-mapview-though-map-library-is-ment and https://developer.android.com/training/maps/index.html

If anyone really wants to use these old platforms, they could just use an old version of the `android-build-box` Docker image.

**Comment by mingchen** [comment]
Good idea.

Do you mind have a PR ?

**Comment by ozmium** [comment]
Yes I can work on this over the next few days.

**Comment by mingchen** [comment]
Fixed by PR #47.
