### ISSUE TITLE
Consider removing all the "extras" items of local libraries, in the Android SDK

### ISSUE THREAD

**Issue by ozmium** [mingchen/docker-android-build-box#49]
The following components are [installed](https://github.com/mingchen/docker-android-build-box/blob/master/Dockerfile#L153-L162) on the Docker images of `android-build-box`:

* extra-android-m2repository
* extra-google-m2repository
* extra-google-google_play_services
* extras-m2repository-constraint-layout-1.0.2
* extras-m2repository-constraint-layout-1.0.1

They will download about 550 MB of library dependencies to the **`$ANDROID_HOME/extras`** folder, which will act like a local Maven repository ("m2repository"). It contains things like Google Play Services, Android Support libraries, RecyclerView, Constraint Layout, etc.

### But I believe these items are never used anymore.

The "extras" folder is deprecated, because gradle will now download these libraries on-demand, from https://maven.google.com -- even for the very old versions. You can browse https://maven.google.com and use the search box to see all the available versions that can be downloaded. The gradle build will just ignore the extras folder, and re-download the libraries anyway.

### More info about the "extras" folder:

* https://stackoverflow.com/questions/43495549/cannot-install-support-repository-and-sync-project-in-android-studio#44926157
* https://stackoverflow.com/questions/31847847/what-is-the-use-of-libraries-in-android-sdk-extras-android-m2repository-com-andr
* Observe that in Android Studio 3, it is not even possible to download the "extras" folder now, using Tools -> SDK Manager. This has been the case since about mid-2019.

----

So please remove the 3 "extras" items from the Docker image, to reduce the overall size by about 550 MB, and make it more efficient.

You can see from the stackoverflow link that the on-demand Maven repo -- https://maven.google.com -- has been available since at least July 2017.

**Comment by mingchen** [comment]
Thanks for reporting this.

I am a little busy recently. PR is welcome.

**Comment by ozmium** [comment]
No problem. I could work on this over the next few days.
