### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by whoamidenny** [mingchen/docker-android-build-box#69]
docker run --rm -v /Users/user/playbook/android-build/var/android-builds/62d024dc-5092-48b1-9aed-28b620efa762/178/178:/project -w '/project' mingc/android-build-box bash -c 'source /root/.bash_profile && chmod 777 gradlew && ./gradlew --configuration-cache && ./gradlew build'
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Downloading https://services.gradle.org/distributions/gradle-6.8-bin.zip
..........10%..........20%..........30%...........40%..........50%..........60%..........70%...........80%..........90%..........100%

Welcome to Gradle 6.8!

Here are the highlights of this release:
 - Faster Kotlin DSL script compilation
 - Vendor selection for Java toolchains
 - Convenient execution of tasks in composite builds
 - Consistent dependency resolution

For more details see https://docs.gradle.org/6.8/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Cannot create service of type DefaultConfigurationCache using DefaultConfigurationCache constructor as there is a problem with parameter #10 of type ConfigurationCacheFingerprintController.
   > Cannot create service of type ConfigurationCacheFingerprintController using ConfigurationCacheFingerprintController constructor as there is a problem with parameter #5 of type FileCollectionFingerprinterRegistry.
      > Cannot create service of type FileCollectionFingerprinterRegistry using method VirtualFileSystemServices$BuildSessionServices.createFileCollectionFingerprinterRegistry() as there is a problem with parameter #1 of type List<FileCollectionFingerprinter>.
         > Could not create service of type FileHasher using BuildSessionServices.createFileHasher().
            > Timeout waiting to lock file hash cache (/project/.gradle/6.8/fileHashes). It is currently in use by another Gradle instance.
              Owner PID: 335
              Our PID: 335
              Owner Operation:
              Our operation:

@mingchen  hello how I can fix this exeption during task execution?

**Comment by mingchen** [comment]
arm64 is not supported yet by Android
