### ISSUE TITLE
while building the project i got this error

### ISSUE THREAD

**Issue by kartheeandroid** [mingchen/docker-android-build-box#7]
File /root/.android/repositories.cfg could not be loaded.
Checking the license for package SDK Patch Applier v4 in /opt/android-sdk/licenses
Warning: License for package SDK Patch Applier v4 not accepted.
Checking the license for package Google Repository in /opt/android-sdk/licenses
Warning: License for package Google Repository not accepted.

**Comment by mingchen** [comment]
Fixed in 4e05771
