### ISSUE TITLE
Docker Hub is missing some of the tags / releases

### ISSUE THREAD

**Issue by Zudoku** [mingchen/docker-android-build-box#73]
Hey, I noticed that some of the tags are missing from Docker Hub: 

https://hub.docker.com/r/mingc/android-build-box/tags

For example `1.23.0` and `1.23.1` are missing. Maybe there is a bug with the  github action that is responsible for uploading the images to Docker Hub? 

https://github.com/mingchen/docker-android-build-box/blob/master/.github/workflows/docker-image.yml

**Comment by mingchen** [comment]
Thanks for reporting this issue. re-tag and pushed to `1.23.1`.
Due to previous error, `1.23.0` was missed and should not use it.
