### ISSUE TITLE
Some tidy up: Delete old build tools, remove unnecessary things, update documentation

### ISSUE THREAD

**Issue by ozmium** [mingchen/docker-android-build-box#75]
I have noticed a few things that could be improved in the latest version of docker-android-build-box (version 1.23.1). The Docker image file size is really big, [currently at 6.7 GB](https://hub.docker.com/r/mingc/android-build-box/tags). This makes it slow for CI build systems to download the image.

I think it could be reduced slightly by removing various things:

### Things that could be removed in the Docker image

* We can remove old build tools of `"build-tools;25.0.3", "build-tools;25.0.2", "build-tools;25.0.1" "build-tools;25.0.0"`. These were used at approximately September 2017, so no modern Android project will be using them now, 4 years later. They can be safely removed. The corresponding `"platforms;android-25"` can also be removed.

* `Kotlin 1.5` and `gradle 7.2` can be removed. All Android apps are setup to use their own specific versions of **Kotlin** and **Gradle**. The system versions of Kotlin and gradle are never used. Android apps will use `gradlew` to download their own version of gradle, as defined in the `gradle-wrapper.properties` file of the project. Similarly, the project's `build.gradle` file will specifiy a unique version of Kotlin to download, using this: `implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"` or this `implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"`

### Documentation updates for Readme.md

* The [Readme.md](https://github.com/mingchen/docker-android-build-box/blob/master/README.md) file says that Python 2 is installed. But this is incorrect. [Python 2.7 is not available by default on Ubuntu 20.04](https://askubuntu.com/questions/1232812/whats-the-default-python-version-in-ubuntu-20-04). It only has Python 3.
* I think it would be better to specify the exact Python version available, which is Python 3.8.10
* I think it would be better to specify exactly which versions of Java are available, and which one is set as the default. Something like this: https://github.com/mingchen/docker-android-build-box/issues/65#issuecomment-945781531

------

If there are no objections, I can create a pull request with all these changes.

**Comment by mingchen** [comment]
Good suggestions, please go ahead to send PR.

**Comment by ozmium** [comment]
@mingchen Thanks for doing this.

Is it possible you could tag this release, so that we can use the Docker image with a tag? Something like `docker pull mingc/android-build-box:1.24.0` ?
