### ISSUE TITLE
jenv local 11 not working

### ISSUE THREAD

**Issue by DeKoServidoni** [mingchen/docker-android-build-box#79]
Trying to set the java to 11 using 
$ jenv local 11
/bin/bash: line 148: jenv: command not found
how can I fix this?

 using the latest version mingc/android-build-box:1.22.0

**Comment by mingchen** [comment]
You need source .bash_profile to get `jenv` in PATH.

Alternative, you can use `update-alternatives` to switch java version. e.g.

```sh
# update-alternatives --set java /usr/lib/jvm/java-8-openjdk-arm64/jre/bin/java
update-alternatives: using /usr/lib/jvm/java-8-openjdk-arm64/jre/bin/java to provide /usr/bin/java (java) in manual mode
root@9b816ba2e3cb:/project# java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```
See [README.md](https://github.com/mingchen/docker-android-build-box) for more about `update-alternatives`.

PS: The default java version is already java 11.
