### ISSUE TITLE
error when running on Oracle Cloud ARM

### ISSUE THREAD

**Issue by a-reznic** [mingchen/docker-android-build-box#90]
uname -a 
Linux instance-20220615-1531 5.15.0-1003-oracle #5-Ubuntu SMP Wed Apr 20 04:51:36 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

uname -m
aarch64

mingc/android-build-box:latest

docker run --rm -v `pwd`:/project mingc/android-build-box bash -c 'cd /project; ./gradlew build'
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /bin/bash: exec format error

**Comment by mingchen** [comment]
Sorry, as far as I know, aarch64 is not supported by Android SDK yet, so this image can also not support it.
