### ISSUE TITLE
[Question] how to Cache NDK

### ISSUE THREAD

**Issue by saeed74** [mingchen/docker-android-build-box#91]
Hi there, 
I have a Linux server that runs a script every 2 min and checks for build apk requests.
so if any request exists it will delete the old temp folder in the server and re-download the source code of my android project from Github to the temp folder and start the building apk.

but the problem is every time this build happens, android-build-box tries to download NDK again and again:

`Install NDK (Side by side) 21.4.7075529`

so is there any way to cache the NDK?
thanks in advance.

**Comment by master-bob** [comment]
Hey, does this issue still persist with the current latest?
